/* Automatically generated by './build/bin/build-entry.ts' */

import Icon from '../packages/icon/index';
import locale from './locale';
import Vue from 'vue'

const components = [
  Icon
];

const install = (
    vue: typeof Vue,
    opts: any = {}
) => {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    vue.component((component as any).name, component);
  });

  vue.prototype.$VARUI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && (window as any).Vue) {
  install((window as any).Vue);
}

export default {
  version: '0.1.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Icon
};
