/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import MessageBox from '../packages/message-box/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Icon from '../packages/icon/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Spinner from '../packages/spinner/index.js';
import Message from '../packages/message/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import ColorPicker from '../packages/color-picker/index.js';
import Container from '../packages/container/index.js';
import Header from '../packages/header/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Footer from '../packages/footer/index.js';
import locale from 'main/locale';
import CollapseTransition from 'main/transitions/collapse-transition';

const components = [
  Button,
  ButtonGroup,
  Icon,
  Row,
  Col,
  Spinner,
  Scrollbar,
  ColorPicker,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$VARUI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.4',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Button,
  ButtonGroup,
  MessageBox,
  Notification,
  Icon,
  Row,
  Col,
  Spinner,
  Message,
  Scrollbar,
  ColorPicker,
  Container,
  Header,
  Aside,
  Main,
  Footer
};
